- hosts: all
  become: true
  become_method: sudo
  vars:
    # python interpreter needs to be set for geerlingguy.mysql (see https://github.com/geerlingguy/ansible-role-mysql/issues/344)
    ansible_python_interpreter: python3
    php_version: '7.3'
    php_enable_php_fpm: true
    php_packages_extra:
      - "php{{php_version}}-zip"
      - "php{{php_version}}-mysql"
    apache_remove_default_vhost: true
    apache_vhosts:
      - servername: "milesloveday.com"
        documentroot: "/vagrant/public_html"
        extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/vagrant/public_html"
  roles:
    - geerlingguy.swap
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-xdebug
    - geerlingguy.apache-php-fpm
    - geerlingguy.composer
    - geerlingguy.mysql
  tasks:
    - name: Vagrant | Bash config
      become: true
      blockinfile:
        path: "/home/vagrant/.bashrc"
        block: |
          export REMOTE_HOST=$(netstat -rn | grep '^0.0.0.0 ' | cut -d ' ' -f10)
          alias phpd="php -d xdebug.remote_autostart=1 -d xdebug.remote_host=$REMOTE_HOST"
          cd /vagrant >& /dev/null
    - name: Vagrant | Permissions
      become: true
      command: "bash /vagrant/scripts/permissions.sh"